-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 22:20:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ComeN'go
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ComeN'go` ;

-- -----------------------------------------------------
-- Schema ComeN'go
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ComeN'go` DEFAULT CHARACTER SET utf8 ;
USE `ComeN'go` ;

-- -----------------------------------------------------
-- Table `ComeN'go`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `activo` BIT(2) NULL,
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComeN'go`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombreusuario` VARCHAR(115) NOT NULL,
  `correo` VARCHAR(80) NOT NULL,
  `telefono` INT(10) NOT NULL,
  `ocupacion` VARCHAR(45) NOT NULL,
  `intereses` VARCHAR(45) NOT NULL,
  `edad` INT(2) NOT NULL,
  `tipo_usuario_idtipo_usuario` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idusuario`, `tipo_usuario_idtipo_usuario`),
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_idtipo_usuario`)
    REFERENCES `ComeN'go`.`tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_tipo_usuario_idx` ON `ComeN'go`.`usuario` (`tipo_usuario_idtipo_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`comanda` (
  `idcomanda` INT NOT NULL AUTO_INCREMENT,
  `activo` BIT(2) NULL,
  `tiempo_aprox` INT NULL,
  `total_pedido` DECIMAL NULL,
  `producto_idproducto` INT NOT NULL,
  `cuenta` DECIMAL NULL,
  PRIMARY KEY (`idcomanda`, `producto_idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComeN'go`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`producto` (
  `idproducto` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `foto_producto` VARCHAR(45) NOT NULL,
  `descripción_producto` DECIMAL(255) NOT NULL,
  `precio_producto` VARCHAR(45) NOT NULL,
  `existencias_producto` INT NULL,
  `activo` TINYINT NULL,
  `comanda_idcomanda` INT NOT NULL,
  `comanda_producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idproducto`, `comanda_idcomanda`, `comanda_producto_idproducto`),
  CONSTRAINT `fk_producto_comanda1`
    FOREIGN KEY (`comanda_idcomanda` , `comanda_producto_idproducto`)
    REFERENCES `ComeN'go`.`comanda` (`idcomanda` , `producto_idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_producto_comanda1_idx` ON `ComeN'go`.`producto` (`comanda_idcomanda` ASC, `comanda_producto_idproducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`tipo_producto` (
  `idtipo_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipoproducto` VARCHAR(45) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `comanda_idcomanda` INT NOT NULL,
  `comanda_producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idtipo_producto`, `producto_idproducto`, `comanda_idcomanda`, `comanda_producto_idproducto`),
  CONSTRAINT `fk_tipo_producto_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `ComeN'go`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_producto_comanda1`
    FOREIGN KEY (`comanda_idcomanda` , `comanda_producto_idproducto`)
    REFERENCES `ComeN'go`.`comanda` (`idcomanda` , `producto_idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tipo_producto_producto1_idx` ON `ComeN'go`.`tipo_producto` (`producto_idproducto` ASC) VISIBLE;

CREATE INDEX `fk_tipo_producto_comanda1_idx` ON `ComeN'go`.`tipo_producto` (`comanda_idcomanda` ASC, `comanda_producto_idproducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `` VARCHAR(45) NULL,
  `tipo_producto_idtipo_producto` INT NOT NULL,
  `tipo_producto_producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idmenu`, `tipo_producto_idtipo_producto`, `tipo_producto_producto_idproducto`),
  CONSTRAINT `fk_menu_tipo_producto1`
    FOREIGN KEY (`tipo_producto_idtipo_producto` , `tipo_producto_producto_idproducto`)
    REFERENCES `ComeN'go`.`tipo_producto` (`idtipo_producto` , `producto_idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_menu_tipo_producto1_idx` ON `ComeN'go`.`menu` (`tipo_producto_idtipo_producto` ASC, `tipo_producto_producto_idproducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`sugerencias_g`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`sugerencias_g` (
  `idsugerencias_g` INT NOT NULL AUTO_INCREMENT,
  `especialidad` VARCHAR(45) NOT NULL,
  `tipo_usuario_idtipo_usuario` INT NOT NULL,
  `menu_idmenu` INT NOT NULL,
  PRIMARY KEY (`idsugerencias_g`, `tipo_usuario_idtipo_usuario`, `menu_idmenu`),
  CONSTRAINT `fk_sugerencias_g_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_idtipo_usuario`)
    REFERENCES `ComeN'go`.`tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sugerencias_g_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `ComeN'go`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sugerencias_g_tipo_usuario1_idx` ON `ComeN'go`.`sugerencias_g` (`tipo_usuario_idtipo_usuario` ASC) VISIBLE;

CREATE INDEX `fk_sugerencias_g_menu1_idx` ON `ComeN'go`.`sugerencias_g` (`menu_idmenu` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`sugerencia_p`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`sugerencia_p` (
  `idsugerencia_p` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_tipo_usuario_idtipo_usuario` INT NOT NULL,
  `menu_idmenu` INT NOT NULL,
  `menu_tipo_producto_idtipo_producto` INT NOT NULL,
  `menu_tipo_producto_producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idsugerencia_p`, `usuario_idusuario`, `usuario_tipo_usuario_idtipo_usuario`, `menu_idmenu`, `menu_tipo_producto_idtipo_producto`, `menu_tipo_producto_producto_idproducto`),
  CONSTRAINT `fk_sugerencia_p_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_tipo_usuario_idtipo_usuario`)
    REFERENCES `ComeN'go`.`usuario` (`idusuario` , `tipo_usuario_idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sugerencia_p_menu1`
    FOREIGN KEY (`menu_idmenu` , `menu_tipo_producto_idtipo_producto` , `menu_tipo_producto_producto_idproducto`)
    REFERENCES `ComeN'go`.`menu` (`idmenu` , `tipo_producto_idtipo_producto` , `tipo_producto_producto_idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sugerencia_p_usuario1_idx` ON `ComeN'go`.`sugerencia_p` (`usuario_idusuario` ASC, `usuario_tipo_usuario_idtipo_usuario` ASC) VISIBLE;

CREATE INDEX `fk_sugerencia_p_menu1_idx` ON `ComeN'go`.`sugerencia_p` (`menu_idmenu` ASC, `menu_tipo_producto_idtipo_producto` ASC, `menu_tipo_producto_producto_idproducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`opciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`opciones` (
  `idopciones` INT NOT NULL AUTO_INCREMENT,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idopciones`, `producto_idproducto`),
  CONSTRAINT `fk_opciones_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `ComeN'go`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_opciones_producto1_idx` ON `ComeN'go`.`opciones` (`producto_idproducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`vinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`vinos` (
  `idvinos` INT NOT NULL AUTO_INCREMENT,
  `nombre_vino` VARCHAR(45) NULL,
  `tipo_vino` VARCHAR(45) NULL,
  `region_vino` VARCHAR(45) NULL,
  `descripcion_vino` VARCHAR(255) NULL,
  `uva` VARCHAR(45) NULL,
  `activo` BIT(2) NULL,
  `menu_idmenu` INT NOT NULL,
  `menu_tipo_producto_idtipo_producto` INT NOT NULL,
  `menu_tipo_producto_producto_idproducto` INT NOT NULL,
  `denominacion` VARCHAR(45) NULL,
  `bodega` VARCHAR(45) NULL,
  `mortaje` VARCHAR(45) NULL,
  PRIMARY KEY (`idvinos`, `menu_idmenu`, `menu_tipo_producto_idtipo_producto`, `menu_tipo_producto_producto_idproducto`),
  CONSTRAINT `fk_vinos_menu1`
    FOREIGN KEY (`menu_idmenu` , `menu_tipo_producto_idtipo_producto` , `menu_tipo_producto_producto_idproducto`)
    REFERENCES `ComeN'go`.`menu` (`idmenu` , `tipo_producto_idtipo_producto` , `tipo_producto_producto_idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vinos_menu1_idx` ON `ComeN'go`.`vinos` (`menu_idmenu` ASC, `menu_tipo_producto_idtipo_producto` ASC, `menu_tipo_producto_producto_idproducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`mesero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`mesero` (
  `idmesero` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario_idtipo_usuario` INT NOT NULL,
  `tipo_usuario_cocina_idcocina` INT NOT NULL,
  PRIMARY KEY (`idmesero`, `tipo_usuario_idtipo_usuario`, `tipo_usuario_cocina_idcocina`),
  CONSTRAINT `fk_mesero_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_idtipo_usuario` , `tipo_usuario_cocina_idcocina`)
    REFERENCES `ComeN'go`.`tipo_usuario` (`idtipo_usuario` , `activo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_mesero_tipo_usuario1_idx` ON `ComeN'go`.`mesero` (`tipo_usuario_idtipo_usuario` ASC, `tipo_usuario_cocina_idcocina` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`cocina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`cocina` (
  `idcocina` INT NOT NULL AUTO_INCREMENT,
  `hacer` VARCHAR(45) NULL,
  `haciendo` VARCHAR(45) NULL,
  `hecho` VARCHAR(45) NULL,
  `hora` TIMESTAMP(4) NULL,
  `mesero_idmesero` INT NOT NULL,
  `mesero_tipo_usuario_idtipo_usuario` INT NOT NULL,
  `mesero_tipo_usuario_cocina_idcocina` INT NOT NULL,
  PRIMARY KEY (`idcocina`, `mesero_idmesero`, `mesero_tipo_usuario_idtipo_usuario`, `mesero_tipo_usuario_cocina_idcocina`),
  CONSTRAINT `fk_cocina_mesero1`
    FOREIGN KEY (`mesero_idmesero` , `mesero_tipo_usuario_idtipo_usuario` , `mesero_tipo_usuario_cocina_idcocina`)
    REFERENCES `ComeN'go`.`mesero` (`idmesero` , `tipo_usuario_idtipo_usuario` , `tipo_usuario_cocina_idcocina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cocina_mesero1_idx` ON `ComeN'go`.`cocina` (`mesero_idmesero` ASC, `mesero_tipo_usuario_idtipo_usuario` ASC, `mesero_tipo_usuario_cocina_idcocina` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`tipo_recompensa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`tipo_recompensa` (
  `idtipo_recompensa` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_recompensa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComeN'go`.`recompensas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`recompensas` (
  `idrecompensas` INT NOT NULL AUTO_INCREMENT,
  `nombre_recompensa` VARCHAR(45) NULL,
  `recompensa` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_tipo_usuario_idtipo_usuario` INT NOT NULL,
  `tipo_recompensa_idtipo_recompensa` INT NOT NULL,
  PRIMARY KEY (`idrecompensas`, `usuario_idusuario`, `usuario_tipo_usuario_idtipo_usuario`, `tipo_recompensa_idtipo_recompensa`),
  CONSTRAINT `fk_recompensas_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_tipo_usuario_idtipo_usuario`)
    REFERENCES `ComeN'go`.`usuario` (`idusuario` , `tipo_usuario_idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recompensas_tipo_recompensa1`
    FOREIGN KEY (`tipo_recompensa_idtipo_recompensa`)
    REFERENCES `ComeN'go`.`tipo_recompensa` (`idtipo_recompensa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_recompensas_usuario1_idx` ON `ComeN'go`.`recompensas` (`usuario_idusuario` ASC, `usuario_tipo_usuario_idtipo_usuario` ASC) VISIBLE;

CREATE INDEX `fk_recompensas_tipo_recompensa1_idx` ON `ComeN'go`.`recompensas` (`tipo_recompensa_idtipo_recompensa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`consumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`consumos` (
  `idconsumos` INT NOT NULL AUTO_INCREMENT,
  `` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_tipo_usuario_idtipo_usuario` INT NOT NULL,
  `comanda_idcomanda` INT NOT NULL,
  `comanda_producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idconsumos`, `usuario_idusuario`, `usuario_tipo_usuario_idtipo_usuario`, `comanda_idcomanda`, `comanda_producto_idproducto`),
  CONSTRAINT `fk_consumos_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_tipo_usuario_idtipo_usuario`)
    REFERENCES `ComeN'go`.`usuario` (`idusuario` , `tipo_usuario_idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumos_comanda1`
    FOREIGN KEY (`comanda_idcomanda` , `comanda_producto_idproducto`)
    REFERENCES `ComeN'go`.`comanda` (`idcomanda` , `producto_idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_consumos_usuario1_idx` ON `ComeN'go`.`consumos` (`usuario_idusuario` ASC, `usuario_tipo_usuario_idtipo_usuario` ASC) VISIBLE;

CREATE INDEX `fk_consumos_comanda1_idx` ON `ComeN'go`.`consumos` (`comanda_idcomanda` ASC, `comanda_producto_idproducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`calorica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`calorica` (
  `idcalorica` INT NOT NULL AUTO_INCREMENT,
  `energia` VARCHAR(45) NULL,
  `proteinas` VARCHAR(45) NULL,
  `grasas_total` VARCHAR(45) NULL,
  `azucares` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_tipo_usuario_idtipo_usuario` INT NOT NULL,
  PRIMARY KEY (`idcalorica`, `usuario_idusuario`, `usuario_tipo_usuario_idtipo_usuario`),
  CONSTRAINT `fk_calorica_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_tipo_usuario_idtipo_usuario`)
    REFERENCES `ComeN'go`.`usuario` (`idusuario` , `tipo_usuario_idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_calorica_usuario1_idx` ON `ComeN'go`.`calorica` (`usuario_idusuario` ASC, `usuario_tipo_usuario_idtipo_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`directorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`directorio` (
  `iddirectorio` INT NOT NULL AUTO_INCREMENT,
  `nombre_restaurante` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `codigo_postal` INT(5) NULL,
  `numero_exterior` INT(3) NULL,
  `especialidad` VARCHAR(45) NULL,
  `resena` VARCHAR(45) NULL,
  `activo` BIT(2) NULL,
  PRIMARY KEY (`iddirectorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComeN'go`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`mesa` (
  `idmesa` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NULL,
  `tiempo` TIME NULL,
  PRIMARY KEY (`idmesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComeN'go`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`tipo_pago` (
  `idtipo_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre_pago` VARCHAR(45) NULL,
  `activo` BIT(2) NULL,
  PRIMARY KEY (`idtipo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ComeN'go`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`pago` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `hora_fecha` TIMESTAMP NULL,
  `tipo_pago_idtipo_pago` INT NOT NULL,
  PRIMARY KEY (`idpago`, `tipo_pago_idtipo_pago`),
  CONSTRAINT `fk_pago_tipo_pago1`
    FOREIGN KEY (`tipo_pago_idtipo_pago`)
    REFERENCES `ComeN'go`.`tipo_pago` (`idtipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pago_tipo_pago1_idx` ON `ComeN'go`.`pago` (`tipo_pago_idtipo_pago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ComeN'go`.`reservacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ComeN'go`.`reservacion` (
  `idreservacion` INT NOT NULL AUTO_INCREMENT,
  `` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_tipo_usuario_idtipo_usuario` INT NOT NULL,
  `mesa_idmesa` INT NOT NULL,
  `pago_idpago` INT NOT NULL,
  PRIMARY KEY (`idreservacion`, `usuario_idusuario`, `usuario_tipo_usuario_idtipo_usuario`, `mesa_idmesa`, `pago_idpago`),
  CONSTRAINT `fk_reservacion_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_tipo_usuario_idtipo_usuario`)
    REFERENCES `ComeN'go`.`usuario` (`idusuario` , `tipo_usuario_idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacion_mesa1`
    FOREIGN KEY (`mesa_idmesa`)
    REFERENCES `ComeN'go`.`mesa` (`idmesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservacion_pago1`
    FOREIGN KEY (`pago_idpago`)
    REFERENCES `ComeN'go`.`pago` (`idpago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reservacion_usuario1_idx` ON `ComeN'go`.`reservacion` (`usuario_idusuario` ASC, `usuario_tipo_usuario_idtipo_usuario` ASC) VISIBLE;

CREATE INDEX `fk_reservacion_mesa1_idx` ON `ComeN'go`.`reservacion` (`mesa_idmesa` ASC) VISIBLE;

CREATE INDEX `fk_reservacion_pago1_idx` ON `ComeN'go`.`reservacion` (`pago_idpago` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
